### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by BytewaveMLP** [BytewaveMLP/sleeti#1]
*Migrated to [Trello](https://trello.com/b/e5rzo48n/sleeti)*, at the suggestion of @LordNature.

**Comment by BytewaveMLP** [comment]
Suggestions should be submitted here.

**Comment by LordNature** [comment]
@BytewaveMLP Why not use trello? It looks better :^)

**Comment by BytewaveMLP** [comment]
@LordNature Because I'm lazy.
I probably should, though.

**Comment by BytewaveMLP** [comment]
@LordNature Done!
