### ISSUE TITLE
Use a version of Parsedown designed to resist XSS

### ISSUE THREAD

**Issue by aidantwoods** [BytewaveMLP/sleeti#5]
Hi there, just trying to track down things that are referencing my anti-xss PR in Parsedown.

I've implemented this security update via a class extension to Parsedown and made it available via composer, hopefully this should get a user-input-safe version of Parsedown out there a lot sooner (given the lack of any hint at a merge any time soon in the core repo 😞).

To grab it:
```bash
composer require aidantwoods/secureparsedown
```

To use it:
```php
<?php

use Aidantwoods\SecureParsedown\SecureParsedown;

$Parsedown = new SecureParsedown;
$Parsedown->setSafeMode(true);
```

And then however you'd normally use Parsedown from then on out, enjoy!

Extension repo here: https://github.com/aidantwoods/SecureParsedown

**Comment by BytewaveMLP** [comment]
Good to know. I appreciate the outreach. :heart:

I'll look into dropping this into sleeti when I can.
